# Environment file for Jupyter notebook examples
name: binder-env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  # Let conda pull in the toolkit and its deps
  - openforcefield

  # Optional(-ish) dependencies used in example(s)
  - nglview
  - qcportal
  - qcengine
  - openmmforcefields
