name: openmm-testing

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "maintenance/.+"

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/openforcefield') || (github.event_name != 'schedule')
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}, RDKit=${{ matrix.cfg.rdkit }}, OpenEye=${{ matrix.cfg.openeye }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        cfg:
          - os: ubuntu-latest
            rdkit: "true"
            openeye: "true"

          - os: macOS-latest
            rdkit: "true"
            openeye: "true"

    env:
      CI_OS: ${{ matrix.cfg.os }}
      RDKIT: ${{ matrix.cfg.rdkit }}
      OPENEYE: ${{ matrix.cfg.openeye }}
      PYVER: ${{ matrix.python-version }}
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      PACKAGE: openforcefield
      PYTEST_ARGS: -r fE --tb=short --cov=openforcefield --cov-config=setup.cfg --cov-append --cov-report=xml

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        name: Install both RDKit and OpenEye toolkits
        if: ${{ matrix.cfg.rdkit == 'TRUE' && matrix.cfg.openeye == 'TRUE' }}
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: devtools/conda-envs/openmm_test_env.yaml
          auto-activate-base: false
      - uses: conda-incubator/setup-miniconda@v2
        name: Install only RDKit
        if: ${{ matrix.cfg.rdkit == 'TRUE' && matrix.cfg.openeye == 'FALSE' }}
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: devtools/conda-envs/rdkit.yaml
          auto-activate-base: false
      - uses: conda-incubator/setup-miniconda@v2
        name: Install with OpenEye toolkits
        if: ${{ matrix.cfg.rdkit == 'FALSE' && matrix.cfg.openeye == 'TRUE' }}
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: devtools/conda-envs/openeye.yaml
          auto-activate-base: false

      - name: Install testing version of OpenMM
        shell: bash -l {0}
        run |
          conda install mamba -c conda-forge -yq
          mamba install -c conda-forge/label/test -c conda-forge "openmm >= 7.5"

      - name: Additional info about the build
        shell: bash -l {0}
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
        shell: bash
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: |
          echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -v .

      - name: Check installed toolkits
        shell: bash -l {0}
        run: |
          if [[ "$OPENEYE" == true ]]; then
            python -c "from openforcefield.utils.toolkits import OPENEYE_AVAILABLE; assert OPENEYE_AVAILABLE, 'OpenEye unavailable'"
          fi
          if [[ "$OPENEYE" == false ]]; then
            if [[ $(conda list | grep openeye-toolkits) ]]; then
              conda remove --force openeye-toolkits --yes
            fi
            python -c "from openforcefield.utils.toolkits import OPENEYE_AVAILABLE; assert not OPENEYE_AVAILABLE, 'OpenEye unexpectedly found'"
          fi
          if [[ "$RDKIT" == true ]]; then
            python -c "from openforcefield.utils.toolkits import RDKIT_AVAILABLE; assert RDKIT_AVAILABLE, 'RDKit unavailable'"
          fi
          if [[ "$RDKIT" == false ]]; then
            if [[ $(conda list | grep rdkit) ]]; then
              conda remove --force rdkit --yes
            fi
            python -c "from openforcefield.utils.toolkits import RDKIT_AVAILABLE; assert not RDKIT_AVAILABLE, 'RDKit unexpectedly found'"
          fi

      - name: Check links
        shell: bash -l {0}
        if: ${{ matrix.cfg.rdkit == 'true' && matrix.cfg.openeye == 'TRUE' }}
        continue-on-error: true
        run: |
          pytest -r fE --tb=short openforcefield/tests/test_links.py

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          PYTEST_ARGS+=" --ignore=openforcefield/tests/test_examples.py"
          PYTEST_ARGS+=" --ignore=openforcefield/tests/test_links.py"
          if [[ "$RDKIT" == true && "$OPENEYE" == true ]]; then
            PYTEST_ARGS+="--doctest-modules"
          fi
          pytest $PYTEST_ARGS $PACKAGE/

      - name: Run example scripts
        shell: bash -l {0}
        continue-on-error: true
        run: |
          if [[ "$RDKIT" == false ]]; then
            PYTEST_ARGS+=" --ignore=examples/check_dataset_parameter_coverage"
            PYTEST_ARGS+=" --ignore=examples/QCArchive_interface"
          fi
          pytest $PYTEST_ARGS openforcefield/tests/test_examples.py

      - name: Run example notebooks
        shell: bash -l {0}
        continue-on-error: true
        run: |
          PYTEST_ARGS+=" --nbval-lax --ignore=examples/deprecated"
          if [[ "$RDKIT" == false ]]; then
            PYTEST_ARGS+=" --ignore=examples/check_dataset_parameter_coverage"
            PYTEST_ARGS+=" --ignore=examples/conformer_energies"
            PYTEST_ARGS+=" --ignore=examples/QCArchive_interface"
            PYTEST_ARGS+=" --ignore=examples/visualization"
          fi
          pytest $PYTEST_ARGS examples/

      - name: Run code snippets in docs
        shell: bash -l {0}
        if: ${{ matrix.cfg.rdkit == 'TRUE' && matrix.cfg.openeye == 'TRUE' }}
        run: |
          pytest -v --doctest-glob="docs/*.rst" docs/

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

