name: Pure-Python Package Build

on:
  release:
    types: 
      - released
      - prereleased
  workflow_dispatch:

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.6
          activate-environment: release-build
          environment-file: devtools/conda-envs/release-build.yaml
          auto-activate-base: false

      - name: Environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Build conda package
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.OMNIA_ANACONDA_TOKEN }}
        run: |
          pushd devtools/conda-recipe/
          conda build --token ${ANACONDA_TOKEN} --user omnia --label rc --python=3.6 -c conda-forge -c omnia .
          popd
